[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aqua_ladder_sc = "C8C53TRUjHe6S29v76Y2srvCoBMR7VMJkWMwtNFJxNCX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./testing_wallet/testing_deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
